feat: Response data for describe
mercator-ocean/copernicus-marine-toolbox pull request #179
Opened 2024-10-21 15:57 UTC by renaudjester

Fix: [CMT-111](https://cms-change.atlassian.net/browse/CMT-111)

Also added some functionality to select the datasetID and/or productID to be able to do fast describe

2024-10-23 13:19 UTC, uriii3 commented on copernicusmarine/catalogue_parser/models.py
> +    """
When doing `copernicusmarine describe --dataset-id med-hcmr-wav-rean-h`, you obtain a n object of these Class, although it doesn't have all products available. Then, the description is not fully correct, no?

2024-10-24 12:02 UTC, uriii3 requested changes

2024-10-24 12:02 UTC, uriii3 commented on copernicusmarine/download_functions/utils.py
> +            values.append(values[-1] + step_value)  # type: ignore
why are we ignoring the types, no? seems weird and a little bit more dangerous, no?

2024-10-25 09:05 UTC, renaudjester commented on doc/usage/describe-usage.rst
> +    copernicusmarine describe -i cmems_mod_glo_phy_my_0.083deg_P1D-m -e services -r datasets,product_id
Then you have almost nothing, just some nested empty dictionary

2024-10-25 09:06 UTC, renaudjester commented on doc/usage/describe-usage.rst
> +    copernicusmarine describe -i cmems_mod_glo_phy_my_0.083deg_P1D-m -e services -r datasets,product_id
I guess with the flexibility comes the complexity. The include exclude are very flexible but you can also make weird stuff. The important I think is that those weird things still make sense and respect the "include" and "exclude" logic at the same time

2024-10-25 09:07 UTC, renaudjester commented on doc/usage/describe-usage.rst
Not sure I am following you 🤔 what change are you suggesting and where?

2024-10-25 09:10 UTC, renaudjester commented on copernicusmarine/python_interface/describe.py
> +        Deprecated. Include all the possible data in output: description, datasets, keywords, and versions.
They do work in the CLI actually :D I keep the default behavior and using them will work the same what as before

2024-10-25 09:34 UTC, renaudjester commented on copernicusmarine/catalogue_parser/models.py
> +    Part of a dataset. Datasets can have multiple parts.
Here is an example of dataset: [stac metadta of an insitu dataset](https://stac.marine.copernicus.eu/metadata/INSITU_GLO_PHYBGCWAV_DISCRETE_MYNRT_013_030/product.stac.json) 
It has links for 3 datasets with: 

- the same datasetID: `cmems_obs-ins_glo_phybgcwav_mynrt_na_irr`
- The same version: `202311`
- But three parts: `history`, `monthly`, `latest`

All of them have different data and different services

2024-10-25 09:40 UTC, renaudjester commented on tests/__snapshots__/test_describe.ambr
>                'chunking_length': 1,
`exclude_none=True` in the model dump, I felt like it is more readable since the `None` don't give information as far as I saw

2024-10-25 09:41 UTC, renaudjester commented on doc/usage/quickoverview.ipynb
Let's do it later when we add everything we need

2024-10-25 09:43 UTC, renaudjester commented on tests/__snapshots__/test_describe.ambr
> +              'minimum_value': 725846400000.0,
> don't know if it would be better to leave the tying of the box open, to float, int (do we have any minimum maximum time in 'datetime' type?)

Can you explicit this please?

2024-10-25 09:44 UTC, renaudjester commented on tests/__snapshots__/test_describe.ambr
> +              'minimum_value': 725846400000.0,
I think timestamps to floats shouldn't be a problem

2024-10-25 09:49 UTC, renaudjester commented on tests/__snapshots__/test_describe_released_date.ambr
> +                        'service_short_name': 'files',
Doesn't seem easy to only set a specific one to `None` https://github.com/pydantic/pydantic/discussions/5461 🤔 And I really like the simplification

I think it's okay to have the convention that if the field that not exists then it's None

2024-10-25 10:00 UTC, renaudjester commented on tests/test_describe.py
> +        assert len(json_result["products"]) >= 270
After the EIS?

2024-10-25 10:00 UTC, renaudjester commented on tests/test_describe.py
> +        assert len(json_result["products"]) >= 270
Added a TODO

2024-10-25 10:04 UTC, renaudjester commented on tests/test_describe.py
> +    def then_I_can_read_it_does_not_contain_weird_symbols(self):
Yeah weird symbols can be in the description and keywords I think

2024-10-25 10:06 UTC, renaudjester commented on tests/test_describe.py
> +        self.then_omi_services_are_not_in_the_catalog()
I don't know

2024-10-25 10:22 UTC, renaudjester commented on tests/test_describe_released_date.py
> +class TestDescribeReleaseDate:
To fit with the name of the file and also because I just created a class `TestDescribe` in the test_describe.py file

2024-10-25 10:23 UTC, renaudjester commented on copernicusmarine/catalogue_parser/catalogue_parser.py
> +from pydantic import BaseModel
The exclude_none, exclude, include functionalities are pretty powerful + it integrated nicely with the sphinx documentation

2024-10-25 10:24 UTC, renaudjester commented on copernicusmarine/core_functions/documentation_utils.py
> +DESCRIBE.update({k: v for k, v in SHARED.items() if k not in DESCRIBE})
I like it 🤭

2024-10-25 10:27 UTC, renaudjester commented on copernicusmarine/catalogue_parser/fields_query_builder.py
> +        assert (
True 🤔 Is it bad to have it there though? let's say we do some modification in the future it could identify some errors, what do you think?

2024-10-25 10:28 UTC, renaudjester commented on copernicusmarine/command_line_interface/group_describe.py
> +            include=include_query,
(see some comments before about flexibility) 
- include: select only the ones you want and show it to you in the nested infrastructure
- exclude: exclude from the result whatever you want

as long as the output makes sense with this I think we are good

2024-10-25 10:30 UTC, renaudjester commented on copernicusmarine/download_functions/utils.py
> +            values.append(values[-1] + step_value)  # type: ignore
It's just that we have some common fields for time and geographical coordinates, which is annoying because time can be a string, so yeah not the best but there are some "if" before, the typing just don't seem to pick it up

2024-10-25 10:31 UTC, renaudjester commented on copernicusmarine/command_line_interface/group_describe.py
> +    "--returned-fields",
Ok let's keep this in mind and dicuss it with the others

2024-10-28 10:35 UTC, uriii3 commented on doc/usage/describe-usage.rst
I'm suggesting that if we have deprecated options, they appear at last in the description (documentation). But to do that, I guess we need to change the base code on python_interface and command_line_interface files.

2024-10-28 10:36 UTC, uriii3 commented on tests/__snapshots__/test_describe.ambr
> +              'minimum_value': 725846400000.0,
Okay, if there is no problem in timestamps to floats then we are good!

2024-10-28 10:39 UTC, uriii3 commented on copernicusmarine/catalogue_parser/fields_query_builder.py
> +        assert (
Mmh then maybe it is not a bad idea yes. Good for me then.

2024-10-28 10:58 UTC, renaudjester commented on doc/usage/describe-usage.rst
I don't know 🤔 Let's ask us the question: what is the deprecation used for? And what do you expect from it?
When we see a deprecation warning about an argument we know that: 

1.  it preferably shouldn't be used
2.  If the argument might still have an influence in the process
3. we will look for a replacement
4. if no direct replacement we need to understand why the change and how can we adapt our code

Now let's look at the information we want to see in helpers, docstrings about each points: 
1. Some deprecation sumup page? Not in the scope of the toolbox right now
2. if it has some influence: basic documentation (like we do in the CLI helper), if no nothing to display
3. and 4. some documentation about migrating from a major version to another

Here is for example the documentation of pydantic for their models: https://docs.pydantic.dev/latest/concepts/models/#model-methods-and-properties before they had an method `.json` renamed to `model_dump_json` and they basically just add a "tip" in the documentation towards the migration page

What do you think? do you see other use cases?

2024-10-28 11:02 UTC, renaudjester commented on tests/test_describe.py
> +        self.then_omi_services_are_not_in_the_catalog()
But I would keep the test and then investigate when it fails or when we refactor the tests (not that much time right now for this and sounds risky to me to delete a test without properly investigating its usefulness)

2024-10-28 14:28 UTC, uriii3 approved these changes

2024-10-28 19:18 UTC, renaudjester commented on copernicusmarine/core_functions/deprecated_options.py
> +                del kwargs[old]
It's normal! There are not replacement for the python API :D

2024-10-28 19:18 UTC, closed without merging